import{S as L,i as c,a as w}from"./assets/vendor-BkVuWn-o.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const b=document.getElementById("search-input"),l=document.getElementById("gallery"),d=document.getElementById("loader"),a=document.getElementById("load-more");let o=1,h="",f=new L(".gallery a",{captionsData:"alt",captionDelay:250});function p(){d.classList.remove("is-hidden"),d.setAttribute("aria-hidden","false")}function m(){d.classList.add("is-hidden"),d.setAttribute("aria-hidden","true")}function v(){l.innerHTML=""}function g(e){return`
    <li class="card">
      <a class="card__link" href="${e.largeImageURL}">
        <img class="card__thumb" src="${e.webformatURL}" alt="${E(e.tags)}" loading="lazy" />
      </a>
      <div class="card__stats">
        <span title="Beğeniler">❤️ ${e.likes}</span>
        <span title="Gösterimler">👁 ${e.views}</span>
        <span title="Yorumlar">💬 ${e.comments}</span>
        <span title="İndirilenler">⬇ ${e.downloads}</span>
      </div>
    </li>
  `}function E(e){return String(e).replace(/[&<>\"']/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[r])}async function y(e,r=1){const i={key:"52761827-accd899221d475ff75a0f470c",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:r};try{return(await w.get("https://pixabay.com/api/",{params:i})).data}catch{throw new Error("An error occurred while fetching the images.")}}const A=document.getElementById("search-form");A.addEventListener("submit",async e=>{e.preventDefault();const r=b.value.trim();if(r){h=r,o=1,v(),p(),a.classList.add("is-hidden");try{const i=await y(r,o),n=i.hits??[];if(!Array.isArray(n)||n.length===0){c.warning({title:"Uyarı",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const t=n.map(g).join("");l.insertAdjacentHTML("beforeend",t),f.refresh(),i.totalHits>n.length&&a.classList.remove("is-hidden")}catch(i){console.error(i),c.error({title:"Hata",message:"An error occurred during the request. Check the console.",position:"topRight"})}finally{m()}}});a.addEventListener("click",async()=>{o+=1,p();try{const e=await y(h,o),r=e.hits??[];if(r.length===0){c.info({title:"Bilgi",message:"You have reached the end of the search results.",position:"topRight"}),a.classList.add("is-hidden");return}const i=r.map(g).join("");l.insertAdjacentHTML("beforeend",i),f.refresh(),e.totalHits<=o*40&&a.classList.add("is-hidden"),window.scrollBy(0,l.querySelector("li").getBoundingClientRect().height*2)}catch(e){console.error(e),c.error({title:"Hata",message:"An error occurred while loading more images.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
